/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * PandamStyle - generated design-system module (ARC-03, D-15).
 *
 * This module is a *generated output* for one design-system instance, not a
 * hand-written layer. It is the single consumption surface a page imports:
 *
 *   import { create, token, recipes, themes, props } from './design.pandamstyle'
 *
 * What it contains, and nothing else:
 *  - the generation marker (systemId + registryDigest + contract version),
 *    which the compiler reads without executing the module;
 *  - theme objects and recipe selectors built on FINITE precompiled data;
 *  - `props`, forwarded to @pandamstyle/core.
 *
 * What it deliberately does not contain: the registry, the policy tables, the
 * Babel plugin, the CSS validator, or any CSS-object interpreter. `create()`
 * and `token()` throw if they are ever reached at runtime, so an uncompiled
 * usage fails loudly instead of silently degrading.
 */

import { DESIGN_SYSTEM_MARKER } from '../../project/graph/resolution';
import { runtimeProjectionOf } from '../../design-system/registry/snapshot';
import { toRecipeSpec, toThemeRefs } from './refs';
import { PATTERN_IDS } from '../../design-system/patterns/compile';

const BANNER = [
  '/**',
  ' * GENERATED BY PANDAMSTYLE - DO NOT EDIT.',
  ' *',
  ' * This file is the consumption surface of one design-system instance.',
  ' * It holds finite, precompiled data only.',
  ' */',
].join('\n');

function jsonLiteral(value) {
  return JSON.stringify(value, null, 2);
}

export function generateDesignSystemModule({ designSystem }) {
  const runtime = runtimeProjectionOf(designSystem.snapshot);
  const systemId = runtime.identity.systemId;
  const marker = {
    abiVersion: runtime.identity.abiVersion,
    compilerContractVersion: runtime.identity.compilerContractVersion,
    designSystem: {
      systemId,
      registryDigest: runtime.identity.registryDigest,
    },
    manifestSchemaVersion: runtime.identity.manifestSchemaVersion,
    capabilities: {
      slots: true,
      compoundVariants: true,
      patterns: true,
      rawDynamicStyles: false,
    },
  };

  const recipeEntries = [];
  for (const [index, [, recipe]] of runtime.recipes.entries()) {
    const spec = toRecipeSpec(recipe, systemId);
    recipeEntries.push(
      [
        `const __pmsRecipe_${index} = /*#__PURE__*/ defineRecipeSelector(${jsonLiteral(spec)});`,
        '',
      ].join('\n'),
    );
  }

  const lines = [
    BANNER,
    '',
    "import { assertAbi, defineRecipeSelector, props as __pmsProps, PmsSelectionError } from '@pandamstyle/core';",
    '',
    'assertAbi(1);',
    '',
    `export const ${DESIGN_SYSTEM_MARKER} = ${jsonLiteral(marker)};`,
    '',
    `export const manifest = ${jsonLiteral(runtime.manifest)};`,
    '',
    'export const props = __pmsProps;',
    '',
    `export const themes = ${jsonLiteral(
      toThemeRefs(Object.fromEntries(runtime.themes), systemId),
    )};`,
    '',
    ...recipeEntries,
    `export const recipes = { ${runtime.recipes
      .map(([id], index) => `[${JSON.stringify(id)}]: __pmsRecipe_${index}`)
      .join(', ')} };`,
    '',
    '// Compile-time only: reaching either at runtime means the PandamStyle',
    '// compiler did not transform this file.',
    'export const token = function token(path) {',
    "  throw new PmsSelectionError({ code: 'PMS_TOKEN_RUNTIME', message: 'token() is compile-time only.', rule: 'generated.token-runtime', context: { path } });",
    '};',
    '',
    'export const create = function create() {',
    "  throw new PmsSelectionError({ code: 'PMS_UNCOMPILED_CREATE', message: 'create() must be transformed by the PandamStyle compiler.', rule: 'generated.create-runtime', context: {} });",
    '};',
    '',
    'export const patterns = Object.freeze({',
    ...PATTERN_IDS.map(
      (id) =>
        `  ${id}() { throw new PmsSelectionError({ code: 'PMS_UNCOMPILED_PATTERN', message: 'patterns.${id}() must be transformed by the PandamStyle compiler.', rule: 'generated.pattern-runtime', context: { patternId: '${id}' } }); },`,
    ),
    '});',
    '',
  ];

  return lines.join('\n');
}
